[window]
opacity = 0.9

[colors]
transparent_background_colors = true

[colors.primary]
background = "#141414"
foreground = "#d4d4d4"

[colors.normal]
black = "#141414"
red = "#c44e55"
green = "#95cc8f"
yellow = "#edd89a"
blue = "#88b4df"
magenta = "#ba5388"
cyan = "#884bba"
white = "#9b9b9b"

[colors.bright]
black = "#242424"
red = "#c8585d"
green = "#addfa6"
yellow = "#fae5a7"
blue = "#8fbde6"
magenta = "#cf5c97"
cyan = "#9e5ccf"
white = "#c7c7c7"
